[package]
name = "jormungand"
version = "0.0.1"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ringbuffer = "0.10.0"
parking_lot = "0.12.1"

[dev-dependencies]
tokio-test = "*"
tokio = { version = "*", features = ["full"] }