[package]
name = "jormungand"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ringbuffer = "0.10.0"
parking_lot = "0.12.1"

[dev-dependencies]
tokio-test = "*"